### ISSUE TITLE
Both releases 0.2.2 and 0.2.4 break visual studio.

### ISSUE THREAD

**Issue by owaisfas** [signalfx/signalfx-dotnet-tracing#520] opened 2022-06-09 17:08 UTC
**Describe the bug**
Both releases 0.2.2 and 0.2.4 are breaking visual studio.  Seems like it misconfigures some environment variables  which visual studio uses.  

**To Reproduce**
1. install visual studio 2022
2. install signalfx .net tracing via msi
3. open  visual studio
4. visual studio does not open (it asks to reset devenv variables but that does not work)

**Comment by pellared** [comment] 2022-06-13 06:18
Hello 👋 

We are sorry to hear about your problems and will do our best to help you solve them. To help you we need more information:


1. Have you used previous versions of  SignalFx .NET Tracing (like 0.1.x) on the same machine?
2. Can you check the env vars on your account (for example, by running `Get-ChildItem Env:` in a PowerShell console)? I have an assumption that some env vars,  like `COR_ENABLE_PROFILING`, are set globally. We do not recommend enabling the auto-instrumentation globally by setting the environment variables on the system or user level.

**Comment by pjanotti** [comment] 2022-06-20 23:06
This issue is not caused by the [SFx.NET](http://sfx.net/) instrumentation itself. Visual Studio hosts the CLR directly and for some reason when a CLR profiler is enabled it uses the devenv.exe.config file from the same location as the devenv.exe instead of using the one under the AppData for the user that typically is used. The devenv.exe.config from AppData contains binding redirects needed for successfully loading VS. This happens before the [SFx.NET](http://sfx.net/) native dll is loaded so it is not caused by it, but, instead by the simply fact that there is a CLR profiler enabled that is correctly configured to be loaded.

It is not recommended to have [SFx.NET](http://sfx.net/) enabled for the whole box, especially a dev box, since it will cause a performance penalty to all managed processes - for which the user is not, typically, interested in collecting observability data. If for some reason a developer still wants to have it enabled for the whole box it is highly recommended to use the environment variable SIGNALFX_PROFILER_EXCLUDE_PROCESSES to exclude processes like devenv.exe, PowerShell.exe, etc. See https://github.com/signalfx/signalfx-dotnet-tracing/blob/581d872bf903a298d304647c329256261b8ea027/docs/advanced-config.md#global-management-settings

@owaisfas I'm closing this issue based on the info above. Let's know if you still have any questions.

**Closed by pjanotti** 2022-06-20 23:06 UTC
